### ISSUE TITLE
Restore previously sent messages - "up button"

### ISSUE THREAD

**Issue by NeatNit** [pfn/qicr#8]
In every command line and IRC client known to man, pressing the up arrow will fill your input box with the previously sent command. As far as I can tell, there is no way to do this in qicr. (maybe with a hardware keyboard it'd work, but I'm using touch only and can't figure out a way to do this)

If it is possible - it's the exact opposite of intuitive, evidently.

It also happens all-too-often that I get disconnected from IRC because of a network failure, that usually fixes itself shortly. The problem is that any message I send while disconnected will result in the input box being cleared and the words "You are not connected" appearing at the bottom of the chat, where my message would have been if I were connected. This is all understandable, if only there was a way to restore my written message... I could spend several minutes typing a message and it'd all be gone in a split-second. And this has happened to me. It hurts. :(

**Comment by pfn** [comment]
fixed by 9daa57a2c84e041ccb3e2b47f32e06ea918d3659
